In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
## Preprocessing the data
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [5]:
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [6]:
## Onehot Encoding the 'Geography' column
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [7]:
## Combinbe Onehot encoded columns with the original dataframe
data = pd.concat([data.drop(['Geography'], axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [8]:
## Split data into features and target variable
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [9]:
## Splitting the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
## Scale these features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
## Save the encoders and scalers for future use
with open('label_encoder_gender.pkl', 'wb') as f:
    pickle.dump(label_encoder_gender, f)
with open('onehot_encoder_geo.pkl', 'wb') as f:
    pickle.dump(onehot_encoder_geo, f)
with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

In [12]:
## ANN Regression Problem Statement
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [13]:
## Build the model
model = Sequential(
    [
        Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
        Dense(32, activation='relu'),
        Dense(1)  # Output layer for regression
    ]
)

## Compile the model
model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])

## summary
model.summary()

c:\ANN_Project\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Setup Tensorboard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [17]:
## Setup EarlyStopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [19]:
# Train the Model
history = model.fit(
    X_train, y_train,
    validation_data = (X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 100385.6641 - mae: 100385.6641 - val_loss: 98543.9062 - val_mae: 98543.9062
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 99708.0547 - mae: 99708.0547 - val_loss: 97164.2578 - val_mae: 97164.2578
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 97293.0547 - mae: 97293.0547 - val_loss: 93608.1406 - val_mae: 93608.1406
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 92496.7500 - mae: 92496.7500 - val_loss: 87627.2109 - val_mae: 87627.2109
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 85394.3203 - mae: 85394.3203 - val_loss: 79701.8906 - val_mae: 79701.8906
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 76819.6328 - mae: 76819.6328 - val_loss: 71146.5234 - val_mae: 71146.5234
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 68191.4688 - mae: 68191.4688 - val_loss: 63446.4023 - val_mae: 63446.4023
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 60894.5000 - mae: 60894.5000 - val_loss: 57590.3672 - val_mae: 57590.3672
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 55780.1953 - mae: 55780.1953 - val_loss: 53893.3438 - val_mae: 53893.3438
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 52823.4727 - mae: 52823.4727 - val_loss: 52035.4766 - val_mae: 52035.4766
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 51410.9336 - mae: 51410.9336 - val_loss: 51346.6445 - val_mae: 51346.6445
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50840.9023 - mae: 50840.9023 - val_loss: 51117.3750 - val_mae: 51117.3750
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50587.4258 - mae: 50587.4258 - val_loss: 51003.7695 - val_mae: 51003.7695
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50458.2422 - mae: 50458.2422 - val_loss: 50932.9609 - val_mae: 50932.9609
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50370.7930 - mae: 50370.7930 - val_loss: 50881.3164 - val_mae: 50881.3164
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50299.0117 - mae: 50299.0117 - val_loss: 50833.7227 - val_mae: 50833.7227
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 50241.0000 - mae: 50241.0000 - val_loss: 50780.0156 - val_mae: 50780.0156
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50185.2344 - mae: 50185.2344 - val_loss: 50734.4766 - val_mae: 50734.4766
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50138.2188 - mae: 50138.2188 - val_loss: 50693.1094 - val_mae: 50693.1094
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50093.3125 - mae: 50093.3125 - val_loss: 50647.2773 - val_mae: 50647.2773
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50050.6367 - mae: 50050.6367 - val_loss: 50624.3711 - val_mae: 50624.3711
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50013.0391 - mae: 50013.0391 - val_loss: 50595.5352 - val_mae: 50595.5352
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49980.2109 - mae: 49980.2109 - val_loss: 50569.6172 - val_mae: 50569.6172
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49943.7266 - mae: 49943.7266 - val_loss: 50538.3281 - val_mae: 50538.3281
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49918.0391 - mae: 49918.0391 - val_loss: 50516.9414 - val_mae: 50516.9414
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49891.8594 - mae: 49891.8594 - val_loss: 50505.4336 - val_mae: 50505.4336
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49860.7227 - mae: 49860.7227 - val_loss: 50496.6953 - val_mae: 50496.6953
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49838.2930 - mae: 49838.2930 - val_loss: 50480.3750 - val_mae: 50480.3750
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49814.8125 - mae: 49814.8125 - val_loss: 50467.9375 - val_mae: 50467.9375
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49793.9297 - mae: 49793.9297 - val_loss: 50448.7930 - val_mae: 50448.7930
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49776.5703 - mae: 49776.5703 - val_loss: 50443.0039 - val_mae: 50443.0039
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49757.0352 - mae: 49757.0352 - val_loss: 50435.2422 - val_mae: 50435.2422
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49740.8945 - mae: 49740.8945 - val_loss: 50434.7734 - val_mae: 50434.7734
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49720.3281 - mae: 49720.3281 - val_loss: 50426.8203 - val_mae: 50426.8203
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49706.0859 - mae: 49706.0859 - val_loss: 50399.4453 - val_mae: 50399.4453
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 49692.7695 - mae: 49692.7695 - val_loss: 50396.4492 - val_mae: 50396.4492
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49680.2109 - mae: 49680.2109 - val_loss: 50392.7773 - val_mae: 50392.7773
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49666.3086 - mae: 49666.3086 - val_loss: 50388.9844 - val_mae: 50388.9844
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49650.2617 - mae: 49650.2617 - val_loss: 50404.8633 - val_mae: 50404.8633
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49638.9062 - mae: 49638.9062 - val_loss: 50399.0586 - val_mae: 50399.0586
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 49624.6641 - mae: 49624.6641 - val_loss: 50378.5195 - val_mae: 50378.5195
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49612.2539 - mae: 49612.2539 - val_loss: 50368.0000 - val_mae: 50368.0000
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49602.1133 - mae: 49602.1133 - val_loss: 50375.2539 - val_mae: 50375.2539
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49591.3242 - mae: 49591.3242 - val_loss: 50373.5742 - val_mae: 50373.5742
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49581.0039 - mae: 49581.0039 - val_loss: 50373.6172 - val_mae: 50373.6172
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49570.6133 - mae: 49570.6133 - val_loss: 50376.8594 - val_mae: 50376.8594
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49560.6016 - mae: 49560.6016 - val_loss: 50369.0117 - val_mae: 50369.0117
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49552.2812 - mae: 49552.2812 - val_loss: 50361.0312 - val_mae: 50361.0312
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49540.1758 - mae: 49540.1758 - val_loss: 50356.8984 - val_mae: 50356.8984
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49533.0625 - mae: 49533.0625 - val_loss: 50368.1055 - val_mae: 50368.1055
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49525.5117 - mae: 49525.5117 - val_loss: 50359.4805 - val_mae: 50359.4805
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49512.9336 - mae: 49512.9336 - val_loss: 50335.8242 - val_mae: 50335.8242
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49508.5781 - mae: 49508.5781 - val_loss: 50344.2617 - val_mae: 50344.2617
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49502.7812 - mae: 49502.7812 - val_loss: 50341.5195 - val_mae: 50341.5195
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49494.5938 - mae: 49494.5938 - val_loss: 50336.7734 - val_mae: 50336.7734
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49488.9414 - mae: 49488.9414 - val_loss: 50353.9258 - val_mae: 50353.9258
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49484.3633 - mae: 49484.3633 - val_loss: 50369.4492 - val_mae: 50369.4492
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49478.6758 - mae: 49478.6758 - val_loss: 50356.4297 - val_mae: 50356.4297
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49471.2188 - mae: 49471.2188 - val_loss: 50348.3867 - val_mae: 50348.3867
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49460.1562 - mae: 49460.1562 - val_loss: 50372.1016 - val_mae: 50372.1016
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49456.9453 - mae: 49456.9453 - val_loss: 50360.8711 - val_mae: 50360.8711
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 49453.7656 - mae: 49453.7656 - val_loss: 50361.0078 - val_mae: 50361.0078

In [20]:
%load_ext tensorboard

In [22]:
%tensorboard --logdir regressionlogs/fit

In [23]:
## Evaluate the model on the test set
test_loss, test_mae = model.evaluate(X_test, y_test)
print(f"Test Loss: {test_loss}, Test MAE: {test_mae}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 50335.8242 - mae: 50335.8242
Test Loss: 50335.82421875, Test MAE: 50335.82421875

In [ ]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

: